
-- root 에서 실행
create database roadkeeperdb;
grant all privileges on roadkeeperdb.* to ohgiraffers@'%';



-- ohgiraffers 에서 실행
use roadkeeperdb;

-- 1. 기존 테이블 삭제 (외래키 관계를 고려하여 자식 테이블부터 삭제)
DROP TABLE IF EXISTS TBL_ACDNT;
DROP TABLE IF EXISTS TBL_VEH_CNT;
DROP TABLE IF EXISTS TBL_CTY_POP;
DROP TABLE IF EXISTS TBL_VEH_TYPE;
DROP TABLE IF EXISTS TBL_CTY;
DROP TABLE IF EXISTS TBL_FAQ;


-- 2. 도시 테이블 (부모 테이블)
CREATE TABLE TBL_CTY (
    CTY_CODE INT NOT NULL COMMENT '도시코드',
    CTY_NM VARCHAR(100) NOT NULL COMMENT '도시명',
    PRIMARY KEY (CTY_CODE)
);


-- 3. 자동차 종류 테이블 (부모 테이블)
CREATE TABLE TBL_VEH_TYPE (
    VEH_CODE INT NOT NULL COMMENT '차종코드',
    VEH_TYPE VARCHAR(100) NOT NULL COMMENT '차종',
    PRIMARY KEY (VEH_CODE)
);


-- 4. 도시별인구 테이블 (TBL_CTY 참조)
CREATE TABLE TBL_CTY_POP (
    CTY_POP_CODE INT NOT NULL COMMENT '인구코드',
    CTY_CODE INT NOT NULL COMMENT '도시코드',
    CTY_POP_YR INT NOT NULL COMMENT '연도',
    CTY_POP INT NOT NULL COMMENT '인구',
    PRIMARY KEY (CTY_POP_CODE),
    CONSTRAINT FK_CTY_POP_CTY FOREIGN KEY (CTY_CODE) REFERENCES TBL_CTY(CTY_CODE)
);


-- 5. 교통사고 테이블 (TBL_CTY, TBL_VEH_TYPE 참조)
CREATE TABLE TBL_ACDNT (
    ACDNT_CODE INT NOT NULL COMMENT '교통사고코드',
    ACDNT_YR INT NOT NULL COMMENT '연도',
    ACDNT_TYPE VARCHAR(100) NOT NULL COMMENT '사고종류',
    ACDNT_NOCS INT NOT NULL COMMENT '교통사고 건수',
    CTY_CODE INT NOT NULL COMMENT '도시코드',
    CAR_CODE INT NOT NULL COMMENT '차종코드',
    PRIMARY KEY (ACDNT_CODE),
    CONSTRAINT FK_ACDNT_CTY FOREIGN KEY (CTY_CODE) REFERENCES TBL_CTY(CTY_CODE),
    CONSTRAINT FK_ACDNT_VEH FOREIGN KEY (CAR_CODE) REFERENCES TBL_VEH_TYPE(VEH_CODE)
);


-- 6. 자동차등록대수 테이블 (TBL_CTY, TBL_VEH_TYPE 참조)
CREATE TABLE TBL_VEH_CNT (
    VEH_CNT_CODE INT NOT NULL COMMENT '자동차등록대수코드',
    VEH_CNT_YR INT NOT NULL COMMENT '연도',
    VEH_CNT_NOCS INT NOT NULL COMMENT '등록건수',
    CTY_CODE INT NOT NULL COMMENT '도시코드',
    VEH_CODE INT NOT NULL COMMENT '차종코드',
    PRIMARY KEY (VEH_CNT_CODE),
    CONSTRAINT FK_VEH_CNT_CTY FOREIGN KEY (CTY_CODE) REFERENCES TBL_CTY(CTY_CODE),
    CONSTRAINT FK_VEH_CNT_VEH FOREIGN KEY (VEH_CODE) REFERENCES TBL_VEH_TYPE(VEH_CODE)
);


-- 7. FAQ 테이블
CREATE TABLE TBL_FAQ (
    FAQ_CODE INT NOT NULL COMMENT 'FAQ_CODE',
    QUESTION VARCHAR(1000) NOT NULL COMMENT '질문',
    ANSWER VARCHAR(1000) NOT NULL COMMENT '대답',
    INST_NM VARCHAR(100) NOT NULL COMMENT '기관명',
    PRIMARY KEY (FAQ_CODE)
);



